let sceneNumber = 1;
const startBtn = document.getElementById('startBtn');
const endMsg = document.getElementById('endMsg');
const startImg = document.getElementById('startImg');
const caption = document.getElementById('caption');

function advanceScene() {
    if (sceneNumber === 1) {
        startImg.src = 'pics/forest2.jpg';
        caption.textContent = 'You venture deeper into the forest. As you get closer, you see a small cabin in the distance. You decide to approach it.';
        sceneNumber++;
    } else if (sceneNumber === 2) {
        startImg.src = 'pics/forest3.jpg';
        caption.textContent = 'You arrive at the cabin and find it abandoned. You search for supplies.';
        sceneNumber++;
    } else if (sceneNumber === 3) { //forest3 image generated by AI
        startImg.style.display = 'none';
        endMsg.style.display = 'block';
        caption.textContent = '';
        startBtn.disabled = true;
    }
}

startBtn.addEventListener('click', advanceScene);